name: Build Android APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
      
      # यहाँ हमने नाम को सही (gram_shakti) कर दिया है
      - run: flutter create --project-name gram_shakti --overwrite .
      
      - run: flutter pub get
      - run: flutter build apk --release
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Gram-Shakti-Final-App
          path: build/app/outputs/flutter-apk/app-release.apk
flutter:
  uses-material-design: true
  assets:
    - index.html
    - admin.html
    - 1770902092682 (1).png
    - 1770902092682 (2).png
    
