name: Build Android APK

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Dependencies
        # यह कमांड आपके फोल्डर के अंदर जाकर काम करेगी
        run: |
          cd $(find . -name "pubspec.yaml" -exec dirname {} \;)
          flutter pub get
        
      - name: Build APK
        run: |
          cd $(find . -name "pubspec.yaml" -exec dirname {} \;)
          flutter build apk --release --no-tree-shake-icons

      - name: Save APK
        uses: actions/upload-artifact@v4
        with:
          name: Gram-Shakti-APK
          # यह फाइल को कहीं से भी ढूंढ कर निकाल लेगा
          path: "**/build/app/outputs/flutter-apk/app-release.apk"
          
