name: Build Android APK

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Dependencies
        # Agar aapka code kisi folder mein hai to niche './' ke baad folder ka naam likhein
        # Agar folder ka naam nahi pata to sirf 'flutter pub get' rehne dein
        run: flutter pub get
        
      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Save APK
        uses: actions/upload-artifact@v4
        with:
          name: Gram-Shakti-APK
          path: build/app/outputs/flutter-apk/app-release.apk
          
